GSA/px-bears-drupal

bears-app/package.json

jest report for storybook was getting hung up on prebuild, passing new `watchAll=false` flag

fix prebuild storybook

---

bears-app/src/shared/components/Accordion/index.jsx
bears-app/src/shared/components/BenefitAccordionGroup/index.jsx

This is set up as a test to include `data-analytics` (static) and `data-analytics-content` (dynamic) for GTM to test event relations in the Benefit Accordion Group component.

includes static and dynamic data attribute for analytics

---

.circleci/config.yml

This PR removes `/var/www/vendor/bin/drush -y config:import --partial --source=modules/custom/usagov_bears/modules/usagov_bears_content/config/optional` command from the pipeline as per the senior developer's request.
- fixes #[Remove config import from pipeline#318](https://github.com/GSA/px-bears-drupal/issues/318)

[318] - Remove config import from the pipeline

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php
usagov_bears/modules/usagov_bears_api/usagov_bears_api.info.yml
usagov_bears/modules/usagov_bears_api/usagov_bears_api.routing.yml

This work builds JSON API of life event.
- fixes #125
To test in sandbox or local site.
navigate to /bears/api/life-event/{id}
The id is the ID of life event form, for example death-of-a-loved-one.

build life event JSON data api

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php
usagov_bears/modules/usagov_bears_api/usagov_bears_api.routing.yml

This work adds function to save JSON data file.
- fixes #125
To test in sandbox or local site.
navigate to http://website/bears/api/life-event/{id}/jsonfile
The id is the ID of life event form, for example death.
For example, the JSON data file is saved to /sites/default/files/bears/api/life_event/death.json
{"data":"Saved JSON data to \/sites\/default\/files\/bears\/api\/life_event\/death.json","method":"GET","status":200}

Save JSON data file

---

bears-app/src/App/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/api/mock-data/current.js
bears-app/src/shared/api/mock-data/current.json
bears-app/src/shared/components/BenefitAccordionGroup/index.jsx
bears-app/src/shared/components/Fieldset/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/Fieldset/index.jsx
bears-app/src/shared/components/LifeEventSection/index.jsx
bears-app/src/shared/components/ResultsView/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/ResultsView/index.jsx
bears-app/src/shared/components/VerifySelectionsView/index.jsx
bears-app/src/shared/locales/en/en.json
bears-app/src/shared/locales/es/es.json

Include a summary of the change, relevant motivation, and context.
- fixes #298 
- fixes #296 
- fixes #276 
[As a user, on a life event form, I may need to answer additional questions if the value of a parent question reveals related child questions from within the same step](https://github.com/GSA/px-bears-drupal/issues/296)	https://github.com/GSA/px-bears-drupal/issues/296
> Did the deceased serve in the active military, naval, or air service?
https://github.com/GSA/px-bears-drupal/assets/37077057/9577533b-3f24-425b-b8d0-cdb6cb6b23e1
[As a user, after completing a life event form, I need to clearly see benefits I may qualify for based on my selections](https://github.com/GSA/px-bears-drupal/issues/276)	https://github.com/GSA/px-bears-drupal/issues/276
[As a user, after completing a …

296 child criteria

---

README.md
bin/cloudgov/cloudgov-aws-creds.sh

This PR creates a script that creates a service-key for us to be able to utilize to use aws s3 commands in cloud.gov.
- fixes #[Create script to use awscli commands against s3 in cloud.gov#409](https://github.com/GSA/px-bears-drupal/issues/409)
1. Make sure you login cloud.gov on your terminal and target your org and space.
```
cf login -a api.fr.cloud.gov --sso
```
2. Change directory to where the script lives.
```
cd bin/cloudgov
```
3. Export the bucket name in your terminal
```
export bucket_name=storage or export bucket_name=dbstorage 
```
4. Execute the following script. Make sure you `source` it!
```
source ./cloudgov-aws-creds.sh 
```
5. If you see the script finds a key and deletes it; make sure you run it again to create the …

[409] - Create script to use awscli commands for s3 in cloud.gov

---

bin/cloudgov/db-backup.sh

This PR makes a quick fix to the database_backup file name in the `db-backup.sh` script.
- fixes #[Fix db name in db backup script and remove gzip part#341](https://github.com/GSA/px-bears-drupal/issues/341)

[341] - fix db name in the backup script

---

usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_agency.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_benefit.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_criteria.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_life_event.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_life_event_form.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_agency.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_agency.teaser.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_benefit.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_benefit.teaser.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_criteria.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_criteria.teaser.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event.teaser.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event_form.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event_form.teaser.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_agency.field_language_toggle.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_benefit.field_language_toggle.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_criteria.field_language_toggle.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_life_event.field_language_toggle.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_life_event_form.field_language_toggle.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.node.field_language_toggle.yml

This work adds language toggle field in benefit content types.
- fixes #243
In sandbox or local server:

add language toggle

---

benefit-finder/src/shared/components/Card/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Chevron/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Heading/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Heading/index.jsx
benefit-finder/src/shared/components/Intro/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/LifeEventSection/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/LifeEventSection/index.jsx
benefit-finder/src/shared/components/Modal/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Modal/index.jsx
benefit-finder/src/shared/components/ObfuscatedLink/index.jsx
benefit-finder/src/shared/components/Radio/index.jsx
benefit-finder/src/shared/components/ResultsView/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/VerifySelectionsView/__tests__/__snapshots__/index.spec.js.snap

This addresses the keyboard a11y issues identified in https://github.com/orgs/GSA/projects/48/views/16?filterQuery=sprint%3A%40current+assignee%3A%22scottqueen-bixal%22&pane=issue&itemId=38495201
- fixes #508
- fixes #511 
11 - “Continue” button skipped in keyboard order.
12 - Modal window is  not keyboard accessible
13 - “Skip to main content” not able to be activated with keyboard
16 - Radio buttons on forms are not correctly formatted and normal keyboard navigation is not expected.
Additionally this fixes
https://github.com/orgs/GSA/projects/48/views/16?filterQuery=sprint%3A%40current+assignee%3A%22scottqueen-bixal%22&pane=issue&itemId=38496463
example:

508 a11y tab order

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php

This PR removes the header of JSON data file.
- fixes #372 
In local or sandbox, 
Navigate to http://benefit-finder-site/bears/api/life-event/{id}/jsonfile
{id} is life event ID, for example, death, retirement, disability.
It saves json data file without header.
For example, the life event "death" json data file has no header.
/sites/default/files/bears/api/life_event/death.json

372 remove header of json data file

---

benefit-finder/src/App/index.jsx
benefit-finder/src/shared/api/mock-data/current.js
benefit-finder/src/shared/api/mock-data/current.json
benefit-finder/src/shared/components/LifeEventSection/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/LifeEventSection/index.jsx
benefit-finder/src/shared/components/Modal/index.jsx
benefit-finder/src/shared/components/StepIndicator/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/StepIndicator/index.jsx

Fixes bug in component that allows current and not current aria elements to be present depending on the comparison of the current index
- fixes #530

530 a11y step indicator

---

.circleci/config.yml

This PR creates an additional workflow that gets triggered daily and redeploys the app to cloud.gov. It makes sure that the additional steps get done to create and place `death.json` to make the `benefit-finder` up and running.
- fixes #[Bug | App gets down after cloud.gov auto restaging#561](https://github.com/GSA/px-bears-drupal/issues/561)

561 create cron to run deploy pipeline daily

---

benefit-finder/src/shared/components/Date/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Date/_index.scss
benefit-finder/src/shared/components/Date/index.jsx
benefit-finder/src/shared/components/LifeEventSection/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/LifeEventSection/index.jsx
benefit-finder/src/shared/locales/en/en.json
benefit-finder/src/shared/locales/es/es.json

This includes functionality to provide an alert banner in line with the date group if there is an error.
- fixes #532 

532 error handling date field

---

benefit-finder/src/shared/components/ProcessList/_index.scss
benefit-finder/src/shared/components/ResultsView/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/ResultsView/index.jsx
benefit-finder/src/shared/locales/en/en.json
benefit-finder/src/shared/locales/es/es.json

Includes updates to resolve the visual `Severity Rating: 2` items which include
- Icon colors “1,2,3” ground color shade is HEX # 0050D8
- Print function was eliminated
- We changed the color of this legend to 3D4551(Dark Medium Gray) based on Amy’s recommendation to improve usability 
- fixes #574 
- Icon colors “1,2,3” ground color shade is HEX # 0050D8
- We changed the color of this legend to 3D4551(Dark Medium Gray) based on Amy’s recommendation to improve usability
- Print function was eliminated

574 update background color on process list

---

benefit-finder/src/shared/components/Date/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Date/index.jsx
benefit-finder/src/shared/components/LifeEventSection/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/LifeEventSection/index.jsx
benefit-finder/src/shared/components/Select/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Select/index.jsx

This works to resolve the required fields query collection on load of render.
- fixes #568 
https://github.com/GSA/px-bears-drupal/assets/37077057/58bb9347-87d1-421b-a83f-9d852cccf78c

568 debug required fields

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php
usagov_bears/modules/usagov_bears_content/usagov_bears_content.module

This work resolves the issue of JSON data building failure with missing eligibility criteria in benefit content.
The JSON data includes benefits for the given life event. 
The benefit content includes many eligibility criteria.
The JSON data building failed when benefit eligibility criteria missing, for example content editor deleted.
Implement solution:
[1] Do not build the missing eligibility criteria.
[2] In benefit edit form, add None option for required select widget of eligibility criteria. This will prevent content editor to select the first option in select widget of missing criteria by accident.

Handle JSON data miss criteria

---

usagov_bears/modules/usagov_bears_content/config/optional/node.type.bears_life_event.yml

This work adds left-menu-english and left-menu-spanish to content type life event.
This enables to build mobile menu and breadcrumb for Benefit Finder app.
- fixes #460 
To test in sandbox
Navigate to Benefit Finder tool in relative URL
/bears/life_event/death
review breadcrumb
review mobile menu

460 add menu to life event

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php

This works generates draft and published json data and file.
It uses URL query parameter mode to control to generate draft or published json data.
It uses the current version of content to build draft json data.
It uses the latest published version of content to build published json data.
- fixes #539 
To test in sandbox,
Edit criteria "Applicant date of birth" with some change in label and save a new version as unpublished.
Edit life event form "Benefit finder: death of a loved one" with some change in title and save a new version as unpublished.
Navigate to following URL to generate draft json data.
/bears/api/life-event/death?mode=draft 
The default value of parameter mode is published.
Navigate to following URL to generate published json data.
/bears/api/life-event/death …

539 draft json data

---

benefit-finder/src/shared/api/apiCalls.js

This updates our fetch logic to handle  `mode=draft` parameter
- fixes #609 
https://github.com/GSA/px-bears-drupal/assets/37077057/8e2e3fb1-b915-47d7-b201-b26a51a0328b

609 update fetch for draft mode

---

benefit-finder/src/shared/components/Accordion/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Accordion/index.jsx

this pulls in uswds js to instantiate the accordion so that the uncaught error can be resolved in dev error boundaries.
- fixes #569

569 resolve accordion error

---

benefit-finder/src/shared/components/BenefitAccordionGroup/__tests__/index.spec.js
benefit-finder/src/shared/components/BenefitAccordionGroup/index.jsx
benefit-finder/src/shared/components/Intro/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/KeyElegibilityCrieriaList/__tests__/index.spec.js
benefit-finder/src/shared/components/KeyElegibilityCrieriaList/index.jsx
benefit-finder/src/shared/components/NoticesList/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/ResultsView/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/ResultsView/index.jsx
benefit-finder/src/shared/components/ShareButton/index.jsx
benefit-finder/src/shared/locales/en/en.json
benefit-finder/src/shared/locales/es/es.json

This works tu update content and translations for the UI.  
- fixes #602 
This document has all the UI based content marked with a light grey background.
https://docs.google.com/document/d/1wt3hIA6vd6XuiS5XCkY5YhMLxysawxu-lnTvAytt2VA/edit
ie.
*Exception: the related benefits section is being developed here ->  https://github.com/GSA/px-bears-drupal/pull/573

602 content UI audit updates

---

usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_life_event_form.default.yml

This work changes the paragraph widget of life event form sections paragraph.
https://www.drupal.org/project/mmf_core_fields
Minimum Multiple Fields [Core Fields] is not Drupal 10 compatible.
- fixes #639

D10 change paragraph widget

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php
usagov_bears/modules/usagov_bears_app/usagov_bears_page/templates/page--bears-life-event.html.twig
usagov_bears/modules/usagov_bears_app/usagov_bears_page/usagov_bears_page.module
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_life_event.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event.teaser.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_life_event.field_draft_json_data_file.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.node.field_draft_json_data_file.yml

This work add and use json data file field in life event for integration with React and TOME static build.
- add draft json data file field in life event
- assign json data file to json data file field when generating json data file
- add attribute json-data-file-path and draft-json-data-file-path in template for React
- fixes #654 
To test in sandbox or local environment
Navigate to url to generate json data file
http://localhost/bears/api/life-event/death/jsonfile
Navigate to url to generate draft json data file
http://localhost/bears/api/life-event/death/jsonfile?mode=draft
Edit life event to see the json data file field.
Navigate to Benefit Finder app to see the data attribute
http://localhost/bears/life_event/death

654 json data file field in life event

---

.circleci/config.yml

This PR removes the code in the pipeline to enable bears module as instructed by the senior dev per below:
- fixes #669

[669] - remove code to enable bears module

---

.circleci/config.yml
mv-benefit-finder-app.sh
mv-usagov_benefit_finder.sh

This PR replaces `bears` with `benefit_finder` in mv-usagov_benefit_finder.sh script. It also updates the module name in the pipeline file.
- fixes #669

Replace BEARS with BENEFIT FINDER

---

benefit-finder/src/shared/components/ResultsView/index.jsx

missing related life events was breaking benefits view
- fixes #(issue)

662 BUG missing related life events breaking benefits view

---

usagov_benefit_finder/config/install/usagov_benefit_finder.settings.yml
usagov_benefit_finder/src/Form/BenefitFinderSettingsForm.php
usagov_benefit_finder/usagov_benefit_finder.links.menu.yml
usagov_benefit_finder/usagov_benefit_finder.routing.yml

This work creates Benefit Finder module configuration page form.
- fixes #684 
To test in sandbox or local: 
Navigate to http://localhost/admin/config
Click "Benefit Finder Configuration" link.
http://localhost/admin/config/usagov_benefit_finder/configuration

684 Benefit Finder module configuration page

---

usagov_benefit_finder/modules/usagov_benefit_finder_api/src/Controller/LifeEventController.php
usagov_benefit_finder/modules/usagov_benefit_finder_api/usagov_benefit_finder_api.module

This work automates JSON data file generating when Benefit Finder content changes.
- fixes #394 
To test in sandbox or local:
Navigate to http://localhost/admin/config/usagov_benefit_finder/configuration
Check automate JSON data file generating.
[x] Automate JSON data file generation
Edit a Benefit Finder content, for example Benefit Finder criteria.
When saving the content change, the system automatically generates JSON data files for all life events in published and draft mode and in English and Spanish version.

394 automate build json file

---

benefit-finder/src/shared/api/__tests__/apiCallsPutData.spec.js

Includes a test against `apiCalls.PUT.Data` to ensure our update method works as expected
- fixes #656 
includes automated tests for 
// an update to currentData if a key match and value match is found
// change if key is found and new value is selected
// no change if key is found but no value match
// no change if no key is found but value matches

656 test for data update based on string values

---

benefit-finder/src/shared/api/__tests__/apiCallsGetElegibilityByCriteria.spec.js

Includes a test against `apiCalls.PUT.Data`,`apiCalls.PUT.DataDate`, `apiCalls.GET.SelectedValueAll`, and `apiCalls.GET.ElegibilityByCriteria`  to ensure our eligibility comparison method works as expected
- fixes #658 
includes automated tests for 
// an update to currentData if a key match and value match is found for a date and a string value
// correctly returns a reduced array of selected objects when apiCalls.GET.SelectedValueAll is called
// correctly assigns eligibility key values to benefits based on selections

658  test for confirming eligibility

---

benefit-finder/src/App/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/api/__tests__/apiCallsUtilsDateEligibility.spec.js
benefit-finder/src/shared/api/apiCalls.js

this updates date eligibility comparisons to epoch format
ie. 
// note: month: === monthIndex
// 0 - 11
const sameDate = { year: 2023, month: 0, day: 1 }
const closerDate = { year: 2023, month: 0, day: 2 } // younger
const furtherDate = { year: 2022, month: 11, day: 30 } // older
{
value: '<01-01-2023', // before 2023 (ie. 2023-01-01)
isSame: false,
isCloser: false,
isFurther: true,
},
- fixes #695

update to epoc comparison when compared to a specific date
