.gitmodules
README.md
bin/cloudgov/container-build
bin/cloudgov/create-service-key-script
bin/cloudgov/deploy-cms
bin/cloudgov/deploy-services
bin/cloudgov/get-s3-access
bin/cloudgov/s3-files-push-from-tmp
bin/cloudgov/setup-egress-for-apps

This PR aims to merge `usagov-2021` sub-module into the repo.

POC | Set up git-submodule

---

mv-bears-app.sh

This works to include a simple bash script that builds our BEARS app and moves the build file to the correct library location for our custom block.

186 poc hello world

---

.circleci/config.yml

This PR fixes the container name reference in the circleci config.yml

Configure circleci pipeline - 110

---

bears-app/jest.config.json
bears-app/src/components/App/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/components/App/index.jsx
bears-app/src/components/shared/Button/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/components/shared/Button/index.jsx
bears-app/src/components/shared/Button/index.stories.jsx

This works to create a button component that aligns with our design style guidance
- fixes #96 

96 buttons

---

bears-app/src/components/shared/api/mock-data/content-data.json
bears-app/src/components/shared/api/mock-data/content-structure.json

Create mock JSON data.
- fixes #107

Create mock JSON data

---

.circleci/config.yml

This PR creates a CircleCI Pipeline to deploy waf via automation.
- fixes [bug/waf has crashed#923](https://github.com/GSA/usagov-benefits-eligibility/issues/923)

Create deploy-waf pipeline

---

.circleci/config.yml

This PR makes sure some additional IPs are whitelisted in the waf.
- fixes [Task/Whitelist Some IPs for WAF#182](https://github.com/GSA/px-bears-drupal/issues/182)

Task/Whitelist Some IPs for WAF

---

bears-app/src/shared/components/Accordion/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/Accordion/__tests__/index.spec.js
bears-app/src/shared/components/Accordion/_index.scss
bears-app/src/shared/components/Accordion/assets/close.svg
bears-app/src/shared/components/Accordion/assets/open.svg
bears-app/src/shared/components/Accordion/index.jsx
bears-app/src/shared/components/Accordion/index.stories.jsx

Baseline component for an accordion.
- fixes #135 

135 accordion

---

bears-app/src/shared/components/ProcessList/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/ProcessList/__tests__/index.spec.js
bears-app/src/shared/components/ProcessList/_index.scss
bears-app/src/shared/components/ProcessList/index.jsx
bears-app/src/shared/components/ProcessList/index.stories.jsx

Baseline component for our process list.
- fixes #149  

149 Process List

---

bears-app/.storybook/manager-head.html

attempts to integrate GTM code snippet in manager-head.html

includes snippet in head

---

usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_benefit.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_life_event_form.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.paragraph.b_levent_elg_criteria.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.paragraph.b_levent_elg_criteria_group.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.paragraph.b_levent_elg_section.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_benefit.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event_form.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.paragraph.b_levent_elg_criteria.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.paragraph.b_levent_elg_criteria_group.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.paragraph.b_levent_elg_section.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_benefit.field_b_life_events.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_life_event_form.field_b_sections_elg_criteria.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_elg_criteria_group.field_b_criterias.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_elg_criteria_group.field_b_description.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_elg_criteria_group.field_b_heading.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_elg_section.field_b_criterias.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.paragraph.field_b_children.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.paragraph.field_b_heading.yml
usagov_bears/modules/usagov_bears_content/config/optional/paragraphs.paragraphs_type.b_benefit_eligibility.yml
usagov_bears/modules/usagov_bears_content/config/optional/paragraphs.paragraphs_type.b_levent_elg_criteria.yml
usagov_bears/modules/usagov_bears_content/config/optional/paragraphs.paragraphs_type.b_levent_elg_criteria_group.yml
usagov_bears/modules/usagov_bears_content/config/optional/paragraphs.paragraphs_type.b_levent_elg_section.yml

Update content entity form:
- Add criteria group in life event form.
- Add hierarchical structure for criteria children input in life event form.
- Change some labels in life event and benefit form.
- fixes #277
To test in sandbox,
In life event form,
Change label: 'Bears Life Event Eligibility Criteria' To label: 'Criteria'
Change label: 'Bears Life Event Eligibility Section' To label: Section
In benefit form,
Change label: 'Bears Benefit Eligibility' To label: 'Benefit Eligibility'
In life event form, criteria children input has hierarchical structure.
In life event form, applicants can add criteria group.

277 update content entity form

---

bears-app/src/App/index.jsx
bears-app/src/shared/api/mock-data/content-data.js
bears-app/src/shared/components/Alert/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/Alert/index.jsx
bears-app/src/shared/components/Hint/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/Hint/index.jsx
bears-app/src/shared/components/LifeEventSection/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/LifeEventSection/index.jsx
bears-app/src/shared/components/Modal/index.jsx
bears-app/src/shared/components/Radio/index.jsx
bears-app/src/shared/components/Select/__tests__/__snapshots__/index.spec.js.snap
bears-app/src/shared/components/Select/index.jsx
bears-app/src/shared/components/StepIndicator/index.jsx
bears-app/src/shared/components/VerifySelectionsView/index.jsx
bears-app/src/shared/locales/en/en.json
bears-app/src/shared/locales/es/es.json

Include a summary of the change, relevant motivation, and context.
- fixes #241 
- fixes #240 
- fixes #239
[As a user, on a life event form, when reviewing my entries I need to see my entries grouped by form step headings](https://github.com/GSA/px-bears-drupal/issues/240)	https://github.com/GSA/px-bears-drupal/issues/240
[As a user, on a life event form, when reviewing my entries I need to see a list of all values from the previous steps inputs](https://github.com/GSA/px-bears-drupal/issues/239)	https://github.com/GSA/px-bears-drupal/issues/239
[As a user, on a life event form, when reviewing my entries I need to be able to confirm my selections](https://github.com/GSA/px-bears-drupal/issues/241)	https://github.com/GSA/px-bears-drupal/issues/241

241 confirm selections

---

bin/cloudgov/db-backup.sh

This PR makes an update to the db-backup script to have the resulting file a unique name on each run.

update db-backup script with unique file name

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php

This work updates the JSON data.
- fixes #125
To test in sandbox or local site.
navigate to /bears/api/life-event/{id}
The id is the ID of life event form, for example death-of-a-loved-one.

update JSON data

---

.github/workflows/stale-branch-maintenance.yml

This PR creates the initial Github Actions workflow for stale branches in the Repo. The workflow runs on a schedule and checks if there are stale branches that match the configurations set in the workflow. If it finds any, it creates an issue and tags both the last committer and the tech-lead on the project.
The workflow file needs to be committed to the `main` branch to be able to run it. So, additional work might be needed after testing. I need this PR to be merged to the `main` branch to be able to test and keep working on it.
- fixes #[establish workflow for stale branches v2#381](https://github.com/GSA/px-bears-drupal/issues/381)
The workflow file needs to be committed to the `main` branch to be able to run it. So, additional work might be needed after testing. I need this PR to be …

establish workflow for stale branches v2

---

.github/workflows/add-comment-stale-branches.yml
.github/workflows/stale-branch-maintenance.yml

Just an additional action workflow file

381 create stale branch action

---

usagov_bears/modules/usagov_bears_app/usagov_bears_page/templates/page--bears-life-event.html.twig

This PR enables TOME to export Benefit Finder JSON data file into static site.
- fixes #496

Export JSON data file to static site

---

benefit-finder/src/App/index.jsx
benefit-finder/src/shared/api/apiCalls.js
benefit-finder/src/shared/components/EmailButton/index.jsx
benefit-finder/src/shared/components/LifeEventSection/index.jsx
benefit-finder/src/shared/components/ResultsView/index.jsx
benefit-finder/src/shared/components/ShareButton/index.jsx
benefit-finder/src/shared/utils/buildURIParameter.js

This updates our app to include new functionality.  
- user can now share or email and encoded link with all the selected param values from a completed form
- when a user paste/ or clicks the link it will take them to the filtered benefits Result View
- when a user navigates back through the application it will represent selected values based on the parameters
- when a user updates the forms values it will remove the query parameter and allow the user to see the updated Results View and share the new state of selected data
- fixes #452 

452 state based param query

---

benefit-finder/src/App/index.jsx
benefit-finder/src/shared/api/apiCalls.js
benefit-finder/src/shared/components/EmailButton/index.jsx
benefit-finder/src/shared/components/LifeEventSection/index.jsx
benefit-finder/src/shared/components/ResultsView/index.jsx
benefit-finder/src/shared/components/ShareButton/index.jsx
benefit-finder/src/shared/utils/buildURIParameter.js

allows the user to navigate with the back button even if required fields are not completed
- fixes #451 

451 back navigation without validation

---

benefit-finder/src/App/_index.scss
benefit-finder/src/shared/components/Date/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/Date/index.jsx
benefit-finder/src/shared/components/LifeEventSection/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/styles/mixins/_index.scss

includes aria descriptions for date labels
a11y note: we use the common approach of leveraging a default input (text) to better control pattern regex, to better describe the expected input we have included an aria content to be available for screen readers
- fixes #531
https://github.com/orgs/GSA/projects/48/views/16?filterQuery=sprint%3A%40current+assignee%3A%22scottqueen-bixal%22&pane=issue&itemId=38629878
https://github.com/GSA/px-bears-drupal/assets/37077057/88ef942d-9bf8-4541-8ec9-7f08a2773509

531 date input descriptions

---

benefit-finder/src/shared/components/EmailButton/index.jsx
benefit-finder/src/shared/components/ResultsView/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/ResultsView/index.jsx
benefit-finder/src/shared/locales/en/en.json
benefit-finder/src/shared/locales/es/es.json

Updates some identified content issues.
Results section text typo
--
[Results section text typo](https://github.com/GSA/px-bears-drupal/issues/454)	https://github.com/GSA/px-bears-drupal/issues/454
[Add space between sentences on results page](https://github.com/GSA/px-bears-drupal/issues/457)	https://github.com/GSA/px-bears-drupal/issues/457
[Change email subject line and body](https://github.com/GSA/px-bears-drupal/issues/458)	https://github.com/GSA/px-bears-drupal/issues/458
[Sentence case sharing options](https://github.com/GSA/px-bears-drupal/issues/459)	https://github.com/GSA/px-bears-drupal/issues/459
[Incorrect Heading and Results Section](https://github.com/GSA/px-bears-drupal/issues/549)	https://github.com/GSA/px-bears-drupal/issues/549
- fixes #454
- fixes #457
- fixes #458
- …

Audit content fixes

---

benefit-finder/src/shared/utils/inputValidation.js

updates date validator logic conditional
- fixes #547 

547 update validator conditional

---

benefit-finder/src/shared/api/apiCalls.js

We have several types of date eligibility conditionals and inequality comparisons like
// date values
// "<01-01-1978"
// "<2years (the deceased died within the last two years)"
// "<18years"
// ">=62years"
// ">=60years"
// ">=50years"
// ">18years"
Javascript also requires us to include some time zone offsets when we start getting detailed on comparisons at the epoch level.
This works to update our date eligibility methods so that it more precisely handles the conditional comparisons are produces correct results.
- fixes #566
There are at least 3 benefit eligibility requirements we can use to test this work in `/death` data
https://github.com/GSA/px-bears-drupal/assets/37077057/8b05abaf-c461-48f9-b8fc-c5c218206f71

566 debug date inequality conditionals

---

.circleci/config.yml

This PR configures the pipeline to create the life event json files and locates them in the correct directories.
- fixes #[Reconfigure pipeline to access all current life-events#584](https://github.com/GSA/px-bears-drupal/issues/584)

584 reconfigure pipeline to use all life events

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.node.bears_life_event_form.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_form_display.paragraph.b_levent_relevant_benefit.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event_form.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.node.bears_life_event_form.teaser.yml
usagov_bears/modules/usagov_bears_content/config/optional/core.entity_view_display.paragraph.b_levent_relevant_benefit.default.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_life_event_form.field_b_json_file.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.node.bears_life_event_form.field_b_relevant_benefits.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_relevant_benefit.field_b_body.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_relevant_benefit.field_b_cta.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_relevant_benefit.field_b_life_event_form.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.field.paragraph.b_levent_relevant_benefit.field_b_link.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.node.field_b_json_file.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.node.field_b_relevant_benefits.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.paragraph.field_b_body.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.paragraph.field_b_cta.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.paragraph.field_b_life_event_form.yml
usagov_bears/modules/usagov_bears_content/config/optional/field.storage.paragraph.field_b_link.yml
usagov_bears/modules/usagov_bears_content/config/optional/paragraphs.paragraphs_type.b_levent_relevant_benefit.yml

This work builds relevant benefits in JSON data.
- Create paragraph "Relevant Benefit".
- Add field "Relevant Benefits" in content type "Life Event Form".
- Update JSON data program to build relevant benefits.
- fixes #477 
To test in sandbox
Navigate to relative URL /bears/api/life-event/death
The JSON data includes Relevant Benefits.

985 - Related Benefits

---

usagov_bears/modules/usagov_bears_content/src/Controller/CheckDataController.php
usagov_bears/modules/usagov_bears_content/usagov_bears_content.routing.yml

This works provide content report tool.
- helps to review the content, criteria, benefit, life event form.
- check data application logic.
- fixes #620 
To test in sandbox
Navigate to URL /benefit-finder/content/report?langcode=en&expanded=true
Query parameters
langcode: en: English (default) es: Spanish
expanded: false: all accordions closed (default) true: all accordions open

620 content report

---

.github/workflows/snyk-security.yml

This PR creates Snyk Scanning.
- fixes #515

[515] - Create Snyk Scanning

---

usagov_bears/modules/usagov_bears_api/src/Controller/LifeEventController.php
usagov_bears/modules/usagov_bears_api/usagov_bears_api.info.yml
usagov_bears/modules/usagov_bears_app/usagov_bears_page/usagov_bears_page.info.yml
usagov_bears/modules/usagov_bears_content/src/Controller/CheckDataController.php
usagov_bears/modules/usagov_bears_content/usagov_bears_content.info.yml
usagov_bears/usagov_bears.info.yml

This work makes benefit finder module Drupal 10 compatible.
- fixes #642

D10 make benefit finder module D10 compatible

---

usagov_benefit_finder/modules/usagov_benefit_finder_api/src/Controller/LifeEventController.php

This work updated the JSON data file path.

429 update json data file path

---

.circleci/config.yml

This PR enables benefit finder modules in pipeline.
- fixes #669

Enable benefit finder modules in pipeline

---

.circleci/config.yml

Enable benefit finder modules in pipeline
- fixes #669

STEP-07:Enable benefit finder modules in pipeline

---

benefit-finder/package-lock.json

updated lock file

---

benefit-finder/src/App/__tests__/__snapshots__/index.spec.js.snap

updated snap

---

benefit-finder/src/App/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/App/index.jsx

Hotfix fetch

---

.github/workflows/cypress.yml

This PR adds GitHub actions for CI/CD run of Cypress tests
- fixes #(https://github.com/GSA/px-bears-drupal/issues/103)

add yaml file for cypress ci-cd run

---

benefit-finder/src/App/_index.scss
benefit-finder/src/shared/components/BenefitAccordionGroup/index.jsx
benefit-finder/src/shared/components/Chevron/_index.scss
benefit-finder/src/shared/components/Fieldset/_index.scss
benefit-finder/src/shared/components/Fieldset/index.jsx
benefit-finder/src/shared/components/LifeEventSection/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/LifeEventSection/_index.scss
benefit-finder/src/shared/components/LifeEventSection/index.jsx
benefit-finder/src/shared/components/VerifySelectionsView/__tests__/__snapshots__/index.spec.js.snap
benefit-finder/src/shared/components/VerifySelectionsView/index.jsx

updates from design requested here https://github.com/orgs/GSA/projects/48/views/16?filterQuery=sprint%3A%40current+assignee%3A%22scottqueen-bixal%22&pane=issue&itemId=43262481
- fixes #693 

693 design audit updates

---

.github/workflows/cypress.yml

This PR resolves the cypress workflow failing issue.
- fixes #[Support | Help with Cypress pipeline#12](https://github.com/GSA/px-benefit-finder/issues/12)

Troubleshoot cypress workflow fail

---

benefit-finder/public/index.html
benefit-finder/src/shared/api/apiCalls.js

in production we query for the url path that the module passes into our template 
- fixes #692 
I've included a test for `death` data in the apps dev index, but you should also be able to run in the drupal env after you build

get fetch url from static markup
